<a href="https://colab.research.google.com/github/logesh2511/Python_example/blob/main/arrayandmatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:

import numpy as np
a=np.random.randint(1,20,(8,5))
print(a)
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

print(a.min())
print(a.min(axis=0))
print(a.min(axis=1))

print(a.max())
print(a.max(axis=0))
print(a.max(axis=1))

print(a.argmax(axis=0))
print(a.argmax(axis=1))

print(a.argmin(axis=0))
print(a.argmin(axis=1))

print(a.mean())
print(a.mean(axis=0))
print(a.mean(axis=1))



[[16 12 19  3 10]
 [ 5  5  3  5 12]
 [ 1  8 12  1 14]
 [ 5 11 15  3  9]
 [ 3  5 10  1 19]
 [ 6 13 15 19 12]
 [19  4 18 11  6]
 [11 11 16 14 12]]
394
[ 66  69 108  57  94]
[60 30 36 43 38 65 58 64]
1
[1 4 3 1 6]
[ 3  3  1  3  1  6  4 11]
19
[19 13 19 19 19]
[19 12 14 15 19 19 19 16]
[6 5 0 5 4]
[2 4 4 2 4 3 0 2]
[2 6 1 2 6]
[3 2 0 3 3 0 1 0]
9.85
[ 8.25   8.625 13.5    7.125 11.75 ]
[12.   6.   7.2  8.6  7.6 13.  11.6 12.8]


In [10]:
a2=a.reshape(2,5,4)


In [3]:
n1=[1,3,4,6,7,9,2]
n2=[4,9,8,5,3,4]
n3=n1+n2
print(n3)

import numpy as np
!pip install numpy


[1, 3, 4, 6, 7, 9, 2, 4, 9, 8, 5, 3, 4]


In [4]:
a1=np.array([1,2,3,4,5])
print(a1)
a2=np.array([3,4,5,6,7])
print(a2)
a3=a1+a2
print(type(a1))
print(type(a2))
print(type(a3))
print(a3)

[1 2 3 4 5]
[3 4 5 6 7]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[ 4  6  8 10 12]


In [5]:
a1=np.array([1,2,3,4,5])
print(a1)
a2=np.array([3,4,5,6,7])
print(a2)
a3=a1+a2
print(type(a1))
print(type(a2))
print(type(a3))
print(a3)

a4=np.array(a1+a2)
print("add",a4)

a5=np.array(a1-a2)
print("sub",a5)

a6=np.array(a1*a2)
print("mult",a6)

a7=np.array(a1/a2)
print("div",a7)

a8=np.array(a1%a2)
print("mod",a8)

[1 2 3 4 5]
[3 4 5 6 7]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[ 4  6  8 10 12]
add [ 4  6  8 10 12]
sub [-2 -2 -2 -2 -2]
mult [ 3  8 15 24 35]
div [0.33333333 0.5        0.6        0.66666667 0.71428571]
mod [1 2 3 4 5]


In [6]:
a1=np.array([1,2,3,4,5])
print(a1)
a2=np.array([3,4,5,6,7])
print(a2)
a3=a1+a2
print(type(a1))
print(type(a2))
print(type(a3))
print(a3)

a4=np.array(a1+a2)
print("add",a4)

a5=np.array(a1-a2)
print("sub",a5)

a6=np.array(a1*a2)
print("mult",a6)

a7=np.array(a1/a2)
print("div",a7)

a8=np.array(a1%a2)
print("mod",a8)

a3=np.sum(a1)
a4=np.sum(a2)
print(a1,"\n",a2)

a3=np.min(a1)
a4=np.min(a2)
print(a3,"\n",a4)

a3=np.max(a1)
a4=np.max(a2)
print(a3,"\n",a4)

a3=np.mean(a1)
a4=np.mean(a2)
print(a3,"\n",a4)

a3=np.median(a1)
a4=np.median(a2)
print(a3,"\n",a4)

[1 2 3 4 5]
[3 4 5 6 7]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[ 4  6  8 10 12]
add [ 4  6  8 10 12]
sub [-2 -2 -2 -2 -2]
mult [ 3  8 15 24 35]
div [0.33333333 0.5        0.6        0.66666667 0.71428571]
mod [1 2 3 4 5]
[1 2 3 4 5] 
 [3 4 5 6 7]
1 
 3
5 
 7
3.0 
 5.0
3.0 
 5.0


In [7]:
import numpy as np
# Corrected array with consistent inner list lengths
a3=np.array([1,2,3,4,5])
print(a3.ndim,"\n",a3,"\n")
a2=np.array([[2,4,5,6,6],[1,2,3,4,5]])
print("\n",a2.ndim)
print(a2,"\n")
a1=np.array([[[1,2,4,5,6,7],[3,5,67,8,9,0],[3,6,9,7,6,0]]])
print(a1.ndim)
print(a1)

1 
 [1 2 3 4 5] 


 2
[[2 4 5 6 6]
 [1 2 3 4 5]] 

3
[[[ 1  2  4  5  6  7]
  [ 3  5 67  8  9  0]
  [ 3  6  9  7  6  0]]]


In [8]:
import numpy as np
# Corrected array with consistent inner list lengths
a1=np.array([1,2,3,4,5])
print(a1.ndim,"\n",a1,"\n")

a2=np.array([[2,4,5,6,6],[1,2,3,4,5]])
print("\n",a2.ndim,"\n",a2,"\n")

a3=np.array([[[1,2,4,5,6,7],[3,5,67,8,9,0],[3,6,9,7,6,0]]])
print("\n",a3.ndim,"\n",a3,"\n")

print("lenght of a1 ",len(a1))
print("lenght of a2 ",len(a2))
print("lenght of a3 ",len(a3))

print(a1.shape)
print(a2.shape)
print(a3.shape)

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

1 
 [1 2 3 4 5] 


 2 
 [[2 4 5 6 6]
 [1 2 3 4 5]] 


 3 
 [[[ 1  2  4  5  6  7]
  [ 3  5 67  8  9  0]
  [ 3  6  9  7  6  0]]] 

lenght of a1  5
lenght of a2  2
lenght of a3  1
(5,)
(2, 5)
(1, 3, 6)
int64
int64
int64
